name: 留言板
description: 欢迎来留言喵～说点什么给作者吧！
title: "[留言] "
labels: ["留言板"]
body:
  - type: textarea
    id: message_content
    attributes:
      label: "✨ 留言内容"
      description: "请在这里写下你想说的话喵～本猫会偷偷看一眼的！"
      placeholder: "在这里写下你的留言内容..."
    validations:
      required: true

  - type: checkboxes
    id: reply_preference
    attributes:
      label: "💡 是否想收到回复？"
      options:
        - label: "是喵～"
        - label: "不用了，我只是路过说声嗨嗨喵～"
