name: Clean Git History

on:
  workflow_dispatch:  # 手动触发清理喵

jobs:
  clean:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout full repo history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 一定要完整历史！

      - name: Install git-filter-repo
        run: |
          pip install git-filter-repo

      - name: Remove MP3s from history
        run: |
          git filter-repo --path-glob '*.mp3' --invert-paths

      - name: Force push cleaned history
        run: |
          git push origin --force --all
          git push origin --force --tags
